server:
  port: 8081
  context-path: /demo
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: hr
mybatis:
  mapper-locations: classpath:com/baizhi/dao/*Mapper.xml
  type-aliases-package: com.baizhi.entity
